#!/bin/sh
export DYLD_FORCE_FLAT_NAMESPACE=1
export DYLD_INSERT_LIBRARIES=/Applications/NeteaseMusic.app/Contents/MacOS/unlock.dylib
exec /Applications/NeteaseMusic.app/Contents/MacOS/NeteaseMusic.org
